### ISSUE TITLE
Google Group does not exist?

### ISSUE THREAD

**Issue by leoc** [nginx-proxy/nginx-proxy#1349] opened 2019-10-31 15:10 UTC
https://groups.google.com/forum/#!forum/nginx-proxy Does not seem to exist or is not public?

I get error messages following the link and cannot find the group by searching manually.

**Comment by tcarecolin** [comment] 2020-11-02 16:59
I have the same issue here want to asks some questions without polluting issues -_-

**Comment by tkw1536** [comment] 2020-11-02 22:19
Duplicate of #1378 and #1502.

**Comment by buchdag** [comment] 2021-06-20 16:13
We're now using [GitHub Discussions](https://github.com/nginx-proxy/nginx-proxy/discussions).

**Closed by buchdag** 2021-06-20 16:13 UTC
