### ISSUE TITLE
Docker Swarm Mode?

### ISSUE THREAD

**Issue by ghost** [nginx-proxy/nginx-proxy#927] opened 2017-09-14 12:30 UTC
Is there any support for Docker Swarm Mode yet?

**Comment by marcwaz** [comment] 2017-10-09 09:25
I have the following errors in swarm mode on one node only:

 upstream server temporarily disabled while connecting to upstream

 connect() failed (110: Connection timed out) while connecting to upstream

Have you planned to support swarm mode ?

**Comment by kennethklee** [comment] 2018-01-18 02:17
works for me on swarm mode, but only with the `latest` and `alpine` images since those are built from `master`.

it's possible the connection timeout is from the ingress network it tries to connect on.

**Comment by biels** [comment] 2018-02-21 20:15
@kennethklee Did you try it with the proxy and applications in different stacks (deployed using docker stack deploy -c docker-compose.yml). This would be the ideal use case because you can deploy and remove individual stacks without messing with the proxy stack.

**Comment by arefaslani** [comment] 2018-03-07 11:23
@kennethklee Can you provide an example with compose file for a docker stack with multiple nodes?

**Comment by arefaslani** [comment] 2018-03-10 07:51
@biels Could you run nginx-proxy in swarm mode with docker stack?

**Comment by loic294** [comment] 2018-03-10 21:04
@arefaslani Did you figure out how to make it work on multiple nodes in Swarm mode. It only seems to connect to services on the same node.

**Comment by biels** [comment] 2018-03-10 21:17
I found a service called traefik that does exactly the same and seems to
work a little bit better. However I'm seriously considering switching over
to kubernetes.

**Comment by arefaslani** [comment] 2018-03-11 11:54
@loic294 All I did was forking the project and manually change [this line](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L17) to `server {{ .Network.IP }}:3000;` and it works. But the problem is that my API runs on port 3000 and my frontend app server runs on 3001 and in this solution I can't have both. 
After that I thought It's a good idea to use variables instead of hardcoding ports. I don't know much about go and it's templating language, but I thought $CurrentContainer in [this line](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L1) is a variable and change [this line](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L17) to `server {{ .Network.IP }}:{{$CurrentContainer}}`. But docker-gen complains that $CurrentContainer is not a variable.

**Comment by loic294** [comment] 2018-03-12 02:58
@arefaslani I almost changed everything for Kubernetes but got it to work with normal Nginx, but without this library. It's far from optimal but for my use case, it works great. In my `docker_stack.yml` file, I created a `nginx` service:

```
nginx:
    image: nginx:latest
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy
    depends_on:
        - metabase
        - api
    deploy:
      placement:
        constraints: [node.role == manager]
```
The placement is important because I manually uploaded the `nginx.conf` file. There is probably a way to sync it between node but it was getting to complex. Now my services in the stack file look something like this (here is the example for metabase):
```
 metabase:
    environment:
      - ...
    image: 'metabase/metabase:latest'
    networks:
      - proxy
      - ...
    depends_on:
      - ...
    ports:
      - 3000:3000 <-- not sure this is required, but I was using it to test
    deploy:
      replicas: 1
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure
```
Finally the `nginx.conf` look something like this:

```
user  www-data;

events {
    worker_connections  1024;
}

http {

	upstream api-app {
			server api:8500;
	}

	server {
			listen 80;
			server_name api.example.com;

			location /  {
					proxy_pass http://api-app;
					proxy_http_version 1.1;   <-- These lines allow websocket to pass.
					proxy_set_header Upgrade $http_upgrade;
					proxy_set_header Connection "upgrade";
					proxy_read_timeout 86400;
			}
	}
	upstream metabase-app {
			server metabase:3000;
	}

	server {
			listen 80;
			server_name metabase.example.com;

			location / {
					proxy_pass http://metabase-app;
			}
	}

}
```
The super important part is that you need to expose the port of your app in the `Dockerfile`.  For example, my api image has a `EXPOSE 8500`. This allow Nginx to know which port to listen to.

I really hope that nginx-proxy solves the issue because there solution is way cleaner.

**Comment by arefaslani** [comment] 2018-05-23 12:50
[docker-gen](https://github.com/jwilder/docker-gen) `Network` structure doesn't have `Port` property.
```go
type Network struct {
    IP                  string
    Name                string
    Gateway             string
    EndpointID          string
    IPv6Gateway         string
    GlobalIPv6Address   string
    MacAddress          string
    GlobalIPv6PrefixLen int
    IPPrefixLen         int
}
```
So one solution is to change [these lines](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L14-L21) in [nginx-proxy](https://github.com/jwilder/nginx-proxy) template to support port through `VIRTUAL_PORT` env variable:
```diff
{{ else if .Network }}
    # {{ .Container.Name }}
    {{ if .Network.IP }}
        {{ if .Container.Env.VIRTUAL_PORT }}
            server {{ .Network.IP }}:{{ .Container.Env.VIRTUAL_PORT }};
        {{ else }}
-          server {{ .Network.IP }} down;
+         server {{ .Network.IP }}:{{ .Container.Env.VIRTUAL_PORT }}; 
        {{ end }}
    {{ else }}
        server 127.0.0.1 down;
    {{ end }}
{{ end }}
```
Then rebuild the image and use `VIRTUAL_PORT` env variable for setting upstreams in swarm mode, correctly. It worked well for me.

**Comment by bfwg** [comment] 2018-07-06 18:55
Any updates?

**Comment by zodern** [comment] 2018-07-06 19:30
I am working on a solution for Meteor Up: [nginx-proxy-swarm-upstream](https://github.com/zodern/nginx-proxy-swarm-upstream).

**Comment by arefaslani** [comment] 2018-07-11 06:05
@zodern This image works well with swarm mode. Formerly I created the [nginx-autoconf](https://github.com/arefaslani/nginx-autoconf) to work with swarm mode. But then I realized that just by changing the original template and rebuilding, this image works well in swarm mode.

**Comment by zodern** [comment] 2018-07-12 02:49
Thanks @arefaslani. That should work for most apps.

There are two main problems that [nginx-proxy-swarm-upstream](https://github.com/zodern/nginx-proxy-swarm-upstream) solves:
1. Adds support for sticky sessions, which requires each task's ip address to be listed as an upstream server in the nginx config. 
2. Allow nginx-proxy and the service tasks to be on different servers

**Comment by arefaslani** [comment] 2018-07-12 21:59
@zodern I don't know what sticky session is, but for problem #2 I use nginx proxy and service tasks in different servers (tested in 2 different machines created by docker machine in a swarm)

**Comment by bfwg** [comment] 2018-07-12 23:13
I end up wrote a customize nginx.conf file alone with `nginx:latest` container. It works perfectly for swarm mode.

**Comment by radyz** [comment] 2018-08-18 23:32
@arefaslani , care to share examples of your service's configurations to make it work in swarm mode accross different nodes :)

**Comment by arefaslani** [comment] 2018-08-19 11:40
# Configuration
## Build your custom Nginx Proxy
Create a Dockerfile like this:
```
FROM jwilder/nginx-proxy
COPY nginx.tmpl nginx.tmpl
```
Copy nginx-proxy's nginx.tmpl alongside your docker file and change it as [this comment](https://github.com/jwilder/nginx-proxy/issues/927#issuecomment-391334432). Then name and build your new proxy with the new template file.

## Docker Compose file

```
version: "3.1"

volumes:
  nginx-certs:
  nginx-vhosts:
  nginx-letsencrypt-challenge:

services:
  app:
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 'ssl://0.0.0.0:3000?key=/etc/nginx/certs/beta.chanka.ir.key&cert=/etc/nginx/certs/beta.api.chanka.ir.crt'"
    volumes:
      - nginx-certs:/etc/nginx/certs
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=production
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=your@email.com

  nginx-proxy:
    image: your/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-letsencrypt-challenge:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.8.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-letsencrypt-challenge:/usr/share/nginx/html
```

Like the example above add `VIRTUAL_PORT` to your service. Note that I added Letsencrypt conf just because everybody wants to use it. the next thing is that I've added `nginx-certs` volume to the Rails app because Puma needs certs to start with HTTPS.

# How does it work
NOTE: All the things I write next is just to clarify what does these configs if you don't understand some parts. If you understand it, go and config yours.

## Volumes
There are 3 volumes in this compose file:
* **nginx-certs**: Let's Encrypt certificates
* **nginx-vhosts**: configuration of vhosts
* **nginx-letsencrypt-challenge**: Letsencrypt challenge files.
## Services
There are 3 services in this compose file:
1. **app**: The application. In this case a `Rails` application with `Puma` web server.
    * Environment Variables:
      * RAILS_ENV: set to production to force Puma to run in production mode.
      * VIRTUAL_HOST: Name of the virtual host (your domain name)
      * VIRTUAL_PORT: The port in which your application runs
      * VIRTUAL_PROTP: Set to https to force your app to serve https traffic.
      * LETSENCRYPT_HOST: Must be equal to `VIRTUAL_HOST`. Letsencrypt uses this variable to generate certs for the specified domain.
      * LETSENCRYPT_EMAIL: Letsencrypt uses this email to send notifications about your certs
    * Volumes:
      * nginx-certs: certificates generated by letsencrypt. Puma needs these certs to start in ssl mode. If you don't use Puma or Rails, This volume is useless.

2. **nginx-proxy**: The reverse proxy.
    * Volumes:
      * nginx-certs: To use certs generated by Letsencrypt
      * nginx-vhosts: Configuration of vhosts
      * nginx-letsencrypt-challenge: To serve chanllenge files to letsencrypt

3. **letsencrypt**:
    * Volumes:
      * nginx-certs: To create/renew Let's Encrypt certificates
      * nginx-vhosts: To change the configuration of vhosts (needed by Let's Encrypt)
      * nginx-letsencrypt-challenge: To write challenge files.

**Comment by jamiejackson** [comment] 2018-09-06 15:42
@arefaslani , thanks for sharing your work. 

However, your patch has drifted from the current state of the repo (which changed in [this commit](https://github.com/jwilder/nginx-proxy/commit/226bfe158fc90b057cec727a7dd36b7a078cbe49#diff-6c19a779564e1e2f88854a4a2fffbb78)):

Your patch:

```patch
{{ else if .Network }}
    # {{ .Container.Name }}
    {{ if .Network.IP }}
        {{ if .Container.Env.VIRTUAL_PORT }}
            server {{ .Network.IP }}:{{ .Container.Env.VIRTUAL_PORT }};
        {{ else }}
-          server {{ .Network.IP }} down;
+         server {{ .Network.IP }}:{{ .Container.Env.VIRTUAL_PORT }}; 
        {{ end }}
    {{ else }}
        server 127.0.0.1 down;
    {{ end }}
{{ end }}
```

[Current](https://github.com/jwilder/nginx-proxy/blob/e80fc0b304bcbcf703d86392394c1a5adb823e3c/nginx.tmpl#L14-L21) (link pinned to a revision, for posterity):

```go
	{{ else if .Network }}
		# {{ .Container.Name }}
		{{ if .Network.IP }}
			server {{ .Network.IP }} down;
		{{ else }}
			server 127.0.0.1 down;
		{{ end }}
	{{ end }}
```

How does this change figure in?

**Comment by jamiejackson** [comment] 2018-09-07 01:01
This, based on @arefaslani's solution, seems to work _so far_: https://gist.github.com/jamiejackson/bac3a440975d1cd98c2d19cd96da1b56

It uses a patch in an attempt to allow for updates to the base template to come through.

**Comment by achrjulien** [comment] 2018-10-10 10:59
Has someone successfully implemented it with multiple node? For me when nginx-proxy needs to contact another node, it ends in a 503 Service Temporarily Unavailable

**Comment by Divxtaman** [comment] 2018-12-01 04:16
@jamiejackson @arefaslani  does it also works with Kubernetes?

**Comment by arefaslani** [comment] 2018-12-01 05:52
@Divxtaman Unfortunately I didn't test it with Kubernetes. I've tested it with Docker Swarm.

**Comment by arefaslani** [comment] 2018-12-01 05:56
@jamiejackson Sorry for the late response. Yes I created this patch for myself almost a year ago. Thank you for updating it. But I think it's a better solution to create a pull request to solve this issue once for all. How about that?

**Comment by orangelynx** [comment] 2019-05-10 18:29
I seem to have the same issue on a single node. I have a pydio container connected with an ssl backend on port 443 (set the VIRTUAL_PORT and VIRTUAL_PROTO env vars accordingly). Works fine in docker compose but with docker stack deploy it fails to find a proper upstream (config shows the proper upstream but with a "down" flag)

**Comment by Bitfroest** [comment] 2019-07-19 19:11
Got stuck with the same issues, finally used traefik.

**Comment by 93Kamuran** [comment] 2019-08-18 06:50
I was allready using Traefik as a reverse proxy traefik was perfect. But  I occurred an issue with using signalr with traefik than I decided to go back to Nginx however I tried either solutions of @jamiejackson and @arefaslani.  I could not achieve to run the proxy in my cluster (swarm mode).

**Comment by tunailgaz** [comment] 2019-10-09 08:49
> [docker-gen](https://github.com/jwilder/docker-gen) `Network` structure doesn't have `Port` property.
> 
> ```go
> type Network struct {
>     IP                  string
>     Name                string
>     Gateway             string
>     EndpointID          string
>     IPv6Gateway         string
>     GlobalIPv6Address   string
>     MacAddress          string
>     GlobalIPv6PrefixLen int
>     IPPrefixLen         int
> }
> ```
> 
> So one solution is to change [these lines](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L14-L21) in [nginx-proxy](https://github.com/jwilder/nginx-proxy) template to support port through `VIRTUAL_PORT` env variable:
> 
> ```diff
> {{ else if .Network }}
>     # {{ .Container.Name }}
>     {{ if .Network.IP }}
>         {{ if .Container.Env.VIRTUAL_PORT }}
>             server {{ .Network.IP }}:{{ .Container.Env.VIRTUAL_PORT }};
>         {{ else }}
> -          server {{ .Network.IP }} down;
> +         server {{ .Network.IP }}:{{ .Container.Env.VIRTUAL_PORT }}; 
>         {{ end }}
>     {{ else }}
>         server 127.0.0.1 down;
>     {{ end }}
> {{ end }}
> ```
> 
> Then rebuild the image and use `VIRTUAL_PORT` env variable for setting upstreams in swarm mode, correctly. It worked well for me.

you saved my time that template looking monkaS to debug EZClap

**Comment by bkraul** [comment] 2019-10-09 09:37
Merge into master for this would be great!

**Comment by MaximMonin** [comment] 2019-11-20 08:01
prepare.sh

`#!/bin/bash

#sudo docker swarm init
sudo docker network create -d overlay --attachable nginx-proxy
#curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl > nginx.tmpl
`

start.sh
`#!/bin/bash

docker stack deploy --compose-file docker-compose.yml nginxproxy
#docker-compose up -d
`
stop.sh

#!/bin/bash
docker stack rm nginxproxy
#docker-compose down

docker-compose.yml
It works ok on manager node as swarm service. If you define replicas 2+ for nginx-proxy container then docker-gen works ok with helder/docker-gen image, but letsencrypt works onlt with 1 replicas.

`version: '3.7'

services:
  nginx:
    image: nginx:1.13.1
    restart: always
    container_name: nginx-proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs

  dockergen:
#    image: jwilder/docker-gen:0.7.3
    image: helder/docker-gen:latest
#    image: kdzch/docker-gen-swarm
    restart: always
    container_name: nginx-proxy-gen
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen:
    deploy:
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - nginx

#    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    command: -notify "docker-label-sighup com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: nginx-proxy-le
    depends_on:
      - nginx
      - dockergen
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ssh-proxy:
    image: mickaelperrin/docker-ssh-proxy
    container_name: ssh-proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    restart: always
    ports:
      - 2222:2222
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  default:
    external:
      name: nginx-proxy
`

**Comment by daveteu** [comment] 2021-03-12 07:24
Apologise if I revive this here but quity
e many post reference here. The current version of nginx.tmpl does look different from this. Anyone have a working version? With the current version, the proxy is still showing only the local connected container, instead of all the replica containers in the swarm.

**Comment by bkraul** [comment] 2021-03-12 12:54
@daveteu this PR has never been merged into the project. As the Japanese would say, akiramete (give up) ...Seems the project maintainer would rather this project fall into obscurity than to accept contributions from the community. I switched to Traefik for swarmed environments. While it is a beast to understand at first, it works perfectly under swarms.

**Comment by daveteu** [comment] 2021-03-12 12:59
thanks @bkraul , didn't know this project is outdated. I wanted nginx to dynamically add upstreams so I can easily scale without touching and changing the "upstream" bit + caching. Traefik fills over complicated and i still need to add nginx nevertheless to do the caching bit (where i have custom lua to do purging).

I wonder if this will work for kubernetes.

**Comment by orangelynx** [comment] 2021-03-12 13:04
@daveteu Not to do any unfair advertising, but +1 for traefik. I too switched to that project after finding no workarounds for problems with this project and traefik is powerful but lightweight, so don't worry about "overkill". I literally just use it for reverse proxying ~10 containers on my personal VPS and it hasn't let me down in the slightest so far.

**Comment by daveteu** [comment] 2021-03-12 18:39
@orangelynx @bkraul thank u, after struggling for a bit, managed to get traefik up and running! May I ask, if I want to put up a nginx cache infront of traefik, my nginx upstream proxy_pass can be any of my 3 servers IP that are behind traefik am i right? The swarm will auto load balance so long the host matches service-name.loadbalancer ?

**Comment by bkraul** [comment] 2021-03-12 18:54
@daveteu, I am not sure what kind of cache you need, but traefik supports a rather large number of what's called Middlewares to achieve a number of purposes. Have you looked into [this] (https://doc.traefik.io/traefik-enterprise/middlewares/http-cache/)?

That said what you described sounds feasible.

**Comment by jamiejackson** [comment] 2021-06-01 20:05
Does this fix the issue? https://github.com/nginx-proxy/nginx-proxy/commit/97a5dec57a6e33a3d4dd93ab22a52c0fffcc0872?branch=97a5dec57a6e33a3d4dd93ab22a52c0fffcc0872&diff=split

It definitely breaks my old patch so I'm hoping I can go without the patch now.

**Comment by tkw1536** [comment] 2022-04-10 17:01
Duplicate of https://github.com/nginx-proxy/nginx-proxy/issues/97

**Closed by tkw1536** 2022-04-10 17:01 UTC
