### ISSUE TITLE
Client IP is internal IP

### ISSUE THREAD

**Issue by unclesamwk** [nginx-proxy/nginx-proxy#401] opened 2016-03-25 16:05 UTC
Hey,

thank you for your very nice proxy.
But ive problem.

The setup of master is, centos 6.5 and installed your nginx-proxy docker.
i run a custom dockercontainer with inside nginx.
in the logfiles i always see the interal ip from the container.

Do you have any idea why?

Greetiings

Sam

**Comment by wader** [comment] 2016-03-25 18:38
You container web server have to look at the `X-Real-IP` or `X-Forwarded-For` header for the remote client address. For nginx have a look at http://nginx.org/en/docs/http/ngx_http_realip_module.html

**Comment by ltarasiewicz** [comment] 2017-02-16 20:01
This is a persistent issue. I'm trying to leverage `X-Forwarded-For` in my backing NGINX containers:

```
real_ip_header X-Forwarded-For;
real_ip_recursive on;
set_real_ip_from 0.0.0.0/0;
```

It's not working, this is what the logs are reporting:

```
172.19.0.1 - - [16/Feb/2017:19:57:34 +0000] "GET / HTTP/1.1" 200 34 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36"
172.19.0.1 - - [16/Feb/2017:19:57:34 +0000] "GET /favicon.ico HTTP/1.1" 200 34 "http://xxxx.com:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36"
```

The same goes for `X-Real-IP`. Both do not help. Will you be able to assist?

**Comment by DuckThom** [comment] 2017-03-11 16:16
I am having the same issue. For me, the ip address that is logged in with `docker logs -f nginx-proxy` is always `172.18.0.1` which is the gateway of the container's network.

```
nginx.1    | blog.local 172.18.0.1 - - [11/Mar/2017:16:05:43 +0000] "GET / HTTP/1.1" 200 4562 "http://blog.local/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
nginx.1    | blog.local 172.18.0.1 - - [11/Mar/2017:16:05:53 +0000] "GET / HTTP/1.1" 200 4563 "http://blog.local/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```

However, when I get the proxy container's 503 page, I do get the correct ip in the log:
```
nginx.1    | 192.168.1.11 192.168.1.1 - - [11/Mar/2017:12:00:53 +0000] "GET / HTTP/1.1" 503 214 "-" "-"
nginx.1    | 192.168.1.11 192.168.1.1 - - [11/Mar/2017:15:34:47 +0000] "GET / HTTP/1.1" 503 214 "-" "-"
```

**Comment by grubshka** [comment] 2018-08-26 22:54
Any update on this ? I'd like to get original IPs in logs for fail2ban, but I can't get them.
I tried using realip module, and changing the log_format...

    set_real_ip_from  10.0.1.1;
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;
    ...
    log_format vhost '$host $http_x_forwarded_for ($remote_addr) - $remote_user [$time_local] '
                     '"$request" $status $body_bytes_sent '
                     '"$http_referer" "$http_user_agent"';

 $remote_addr is still the gateway IP, and $http_x_forwarded_for is empty.

    xxx.test.com - (10.0.1.1) - - [26/Aug/2018:22:42:43 +0000] "GET / HTTP/1.1" 200 7236 "-" "-"

**Comment by zoh48gz04** [comment] 2019-06-18 12:13
Also having this issue, any updates on this?

**Comment by bhupeshchugh** [comment] 2019-11-07 07:58
Any resolution on this, i am also facing this same issue.

**Comment by jantoine1** [comment] 2019-11-14 02:24
I am also getting a gateway IP address forwarded to the web server container. The interesting thing is that it's not always the gateway of the network that the web server i'm accessing is on. I have several web servers in their own docker-compose projects, each on its own network, and connect the nginx proxy container to each of those networks. The gateway IP that get's forwarded always seems to be the gateway IP of whichever network is at the top of the list when running `docker inspect` on the nginx proxy container.

I'll continue to dig into this, but any help/direction is appreciated.

**Comment by jantoine1** [comment] 2019-11-14 09:28
This seems to be a duplicate of #133 where I've provided some insight into what was causing this issue for me and how I resolved it.

**Comment by tkw1536** [comment] 2022-04-10 14:12
Closing because duplicate.

**Closed by tkw1536** 2022-04-10 14:12 UTC
