### ISSUE TITLE
Static files request 504 timeout.

### ISSUE THREAD

**Issue by Tairy** [nginx-proxy/nginx-proxy#563] opened 2016-09-08 04:02 UTC
I use nginx-proxy as a router server,  the backend container is [ui-for-docker](https://github.com/kevana/ui-for-docker), but the first request always faile because some static files get a 504 gateway timeout error.

**Comment by tkw1536** [comment] 2022-04-10 16:50
This doesn't really provide a lot of information.
Since the issue is several years old I am closing it, please reopen if still relevant.

**Closed by tkw1536** 2022-04-10 16:50 UTC
Labels: status/needs-more-info
