### ISSUE TITLE
How to route subdirectory of a domain to a separate container or docker host?

### ISSUE THREAD

**Issue by tahir-gvs** [nginx-proxy/nginx-proxy#712] opened 2017-02-10 06:13 UTC
I see it is possible to add custom virtual host config files by mounting /etc/nginx/vhost.d directory. 
So if we want to manually route a subdomain we can create a subdomain.domain.com.conf file in vhost.d with a proxy_pass directive. 

But what if we want to route subdomain.domain.com to one container and subdomain.domain.com/app to another container or directly to a server running on docker host. Is this possible?

**Comment by NoahO** [comment] 2017-04-05 06:42
I agree, this is a use case for me too. I have 5 apps on the one box, pairing this with letsencrypt-nginx-proxy-companion means I must have 5 hostnames and 5 letsencrypt certificates for the same proxy server on the one box... It's very wasteful of letsencrypt's resources.

**Comment by bwoodmansee** [comment] 2017-05-31 04:05
👍, I'm interested in this use case as well

**Comment by hydra1983** [comment] 2017-05-31 05:18
You mean things like this?

```yaml
- VIRTUAL_HOST=${SUBDOMAIN}.${DOMAIN}
- VIRTUAL_PORT=6203
- VIRTUAL_PATH=~* ^(\/advisor-auth)(\/api)(\/.*)?$$
- VIRTUAL_PATH_REWRITE=^(\/advisor-auth)(\/api)(\/.*)$$ $$2$$3
```

**Comment by skleeschulte** [comment] 2017-08-14 16:14
@hydra1983 Is there a container where these variables can be used, or did you just make them up?

**Comment by ciokan** [comment] 2017-08-29 06:56
Anyone managed to get this working?

**Comment by rahimrahman** [comment] 2017-10-27 04:22
I got this to work but I had to hard-code the `/etc/nginx/vhost.d/{your-virtual-hostname}` file.  So my `docker-compose.yml` file looks like this:

```
version: '3.1'
services:
  web:
    image: username/web:latest
    environment:
      - VIRTUAL_HOST=www.example.com

  api:
    image: fieldops360/app_links:latest
    environment:
      - VIRTUAL_HOST=the_api
      - VIRTUAL_PORT=3000

  nginx-proxy:
    container_name: nginx_proxy
    image: jwilder/nginx-proxy:alpine
    depends_on:
      - web
      - api
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
```

and my `/etc/nginx/vhost.d/www.example.com` file:

```
        location ^~ /api {
                proxy_pass http://the_api/;
        }
```

`proxy_pass` value of `http://the_api/` and `http://the_api` (note the trailing slash) will yield two different behaviors: first one will take you to the root of `the_api` whereas the second one will pass on as `http://the_api/api`.

Hope that helps somebody.

**Comment by KrzysztofMadejski** [comment] 2020-03-31 13:17
Duplicate of #47 and #190

**Comment by buchdag** [comment] 2021-07-19 19:13
This features has been added to the `dev` branch with #1607 

It's available now on the `dev` images `nginxproxy/nginx-proxy:dev` and `nginxproxy/nginx-proxy:dev-alpine`. Testing and feedback are welcome, the docs for the feature is [here](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing) and there is [another PR](https://github.com/nginx-proxy/nginx-proxy/pull/1699) opened for additional improvements and comments.

**Closed by buchdag** 2021-07-19 19:13 UTC
Labels: kind/feature-request, scope/path-based-routing

**Comment by genaroVL** [comment] 2021-09-12 07:14
> This features has been added to the `dev` branch with #1607
> 
> It's available now on the `dev` images `nginxproxy/nginx-proxy:dev` and `nginxproxy/nginx-proxy:dev-alpine`. Testing and feedback are welcome, the docs for the feature is [here](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing) and there is [another PR](https://github.com/nginx-proxy/nginx-proxy/pull/1699) opened for additional improvements and comments.
I have two containers, with the same virtual host, one has a virtual path of "/" and my second container has another virtual path, and it does not recognize me.

`  api:
    build:
      context: ./java
      args:
        - JAR_FILE=*.jar
    container_name: backendSpring      
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M 
       - VIRTUAL_HOST=yipitest.tk,www.yipitest.tk
       - VIRTUAL_PATH=/api
       - VIRTUAL_PORT=443
       - VIRTUAL_PROTO=https
       - SERVER_PORT=443 
  

  frontvue:
    build:
      context: ./vue/informative-web 
    container_name: frontVue
    depends_on:     
      - api
      - nginx-proxy
      - letsencrypt

    environment:
      - VIRTUAL_HOST=domain.tk,www.domain.tk
      - VIRTUAL_PATH=/`

**Comment by junderw** [comment] 2021-09-12 07:40
if you use `VIRTUAL_PATH=/api` then it will route all requests to /api* to that container.

But your container will still receive the /api path and should be able to understand it. If your container throws an error because "I don't understand /api path" then you should add `VIRTUAL_DEST=/`

However, any links generated by the container (ie. if the container is a web app etc.) must use relative paths for resolving, OR have some way to be told "please add /api at the beginning of your links because my nginx won't route to you without /api"

**Comment by genaroVL** [comment] 2021-09-12 19:51
really the problem comes that it does not let me have the same virtual host, although they have different virtual path, that is, only one takes the virtual host, and the other ignores it, I can access my api, but not my page.

**Comment by genaroVL** [comment] 2021-09-12 19:51
really the problem comes that it does not let me have the same virtual host, although they have different virtual path, that is, only one takes the virtual host, and the other ignores it, I can access my api, but not my page
