### ISSUE TITLE
Doesn't seem to work with new docker networking

### ISSUE THREAD

**Issue by xoredg** [nginx-proxy/nginx-proxy#305] opened 2015-11-29 16:15 UTC
It doesn't seem to work with the new docker networking features. i.e. `--x-networking` for example on docker compose. I'm not really sure if it should to begin with, but it would be handy.
I'm running a SPA, API and DB under a new networked setup and nginx-proxy gives a 503 even when the LB has the `VIRTUAL_HOST` env var. Are you aware of this?

**Comment by thaJeztah** [comment] 2015-11-29 17:28
possible duplicate of https://github.com/jwilder/nginx-proxy/issues/304?

**Comment by blackxored** [comment] 2015-11-30 19:47
It might be. The only difference is that I'm talking local networking, but yes the lacking support for the new networking API definitely seems like the culprit.

**Comment by modius** [comment] 2015-12-15 05:54
:+1: 

Trying to move from links to networking and this definitely appears to be an issue.

> While links are still supported in this limited capacity, you should avoid them in preference of Docker networks. The link feature is expected to be deprecated and removed in a future release.

https://docs.docker.com/engine/userguide/networking/dockernetworks/

**Comment by modius** [comment] 2015-12-15 06:12
@schmunk42 did this commit make it into the Docker image? 

https://github.com/jwilder/docker-gen/commit/fdf292247a233d4775e258979b3fa5e6b1c187b9

**Comment by md5** [comment] 2015-12-19 07:00
@modius No. But see https://github.com/jwilder/docker-gen/pull/144

**Comment by tkw1536** [comment] 2022-04-10 14:06
Related issue is closed, closing.

**Closed by tkw1536** 2022-04-10 14:06 UTC
