### ISSUE TITLE
ARM7 32bit not working

### ISSUE THREAD

**Issue by Omega1902** [nginx-proxy/nginx-proxy#1742] opened 2021-08-20 17:09 UTC
[working.zip](https://github.com/nginx-proxy/nginx-proxy/files/7026640/working.zip)
Could not make the version 0.9.0 or 0.9.2 alpine working on my raspberry pi 3.
Port 80 always showed the standard nginx - screen, port 443 didn't respond at all.

PI information from neofetch:
OS: Raspbian GNU/Linux 10 (buster) armv7l 
Host: Raspberry Pi 3 Model B Rev 1.2 

Switching to debian:jessie solved the issue - alpine would be nice to have.

**Comment by tkw1536** [comment] 2021-08-20 17:52
That's odd, I did explicitly run the `0.9.0` tests on a raspberry pi, which worked without issue at the time. 
But I never actually ran a production deployment on one. 

@Omega1902 would you be willing to share the exact setup (docker-compose.yml or equivalent) and / or logs so we can try to see where the issue is?

Maybe we should also try and run the tests on other architectures via qemu on github actions?

**Comment by Omega1902** [comment] 2021-08-22 05:42
Sure. I've started with this example:
https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache

Working configuration is attached to the issue. Just adding -alpine to the proxy version in the Dockerfile will lead to the described behaviour.

**Comment by buchdag** [comment] 2023-12-20 09:47
Failed to reproduce the issue, closing.

**Closed by buchdag** 2023-12-20 09:47 UTC
