### ISSUE TITLE
Version 1.2 breaks `podman` or `moby-engine` comatability. (Can't infer current container from containerID)

### ISSUE THREAD

**Issue by heyakyra** [nginx-proxy/nginx-proxy#2178] opened 2023-02-17 00:08 UTC
On `nginx-proxy` v 1.2 and later, I have been hitting this:
```
Feb 16 17:06:58 vps-78bb3f645.vps.ovh.us nginx-proxy[2675937]: forego      | starting dockergen.1 on port 5100
Feb 16 17:06:58 vps-78bb3f645.vps.ovh.us nginx-proxy[2675937]: dockergen.1 | 2023/02/16 17:06:58 Template error: template: nginx.tmpl:24:18: executing "nginx.tmpl" at <$globals.CurrentContainer.Networks>: nil pointer evaluating interface {}.Networks
Feb 16 17:06:58 vps-78bb3f645.vps.ovh.us nginx-proxy[2675937]: forego      | starting dockergen.1 on port 5100
Feb 16 17:06:58 vps-78bb3f645.vps.ovh.us nginx-proxy[2675937]: dockergen.1 | 2023/02/16 17:06:58 Template error: template: nginx.tmpl:24:18: executing "nginx.tmpl" at <$globals.CurrentContainer.Networks>: nil pointer evaluating interface {}.Networks
Feb 16 17:06:58 vps-78bb3f645.vps.ovh.us nginx-proxy[2675937]: forego      | starting dockergen.1 on port 5100
Feb 16 17:06:58 vps-78bb3f645.vps.ovh.us nginx-proxy[2675937]: dockergen.1 | 2023/02/16 17:06:58 Template error: template: nginx.tmpl:24:18: executing "nginx.tmpl" at <$globals.CurrentContainer.Networks>: nil pointer evaluating interface {}.Networks
Feb 16 17:06:58 vps-78bb3f645.vps.ovh.us nginx-proxy[2675937]: forego      | starting dockergen.1 on port 5100
Feb 16 17:06:58 vps-78bb3f645.vps.ovh.us nginx-proxy[2675937]: dockergen.1 | 2023/02/16 17:06:58 Template error: template: nginx.tmpl:24:18: executing "nginx.tmpl" at <$globals.CurrentContainer.Networks>: nil pointer evaluating interface {}.Networks
```
Version 1.1 is unaffected. Where does the template file get these values from?

This also seems to impact `acme-companion`, but there seems to be no working version that I could find. 
```
Feb 17 00:05:02 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29442]: 2023/02/17 00:05:02, Error: can't get my container ID !
Feb 17 00:05:02 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29442]: Error: can't get nginx-proxy container ID !
Feb 17 00:05:02 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29442]: Check that you are doing one of the following :
Feb 17 00:05:02 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29442]:        - Use the --volumes-from option to mount volumes from the nginx-proxy container.
Feb 17 00:05:02 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29442]:        - Set the NGINX_PROXY_CONTAINER env var on the letsencrypt-companion container to the name of the nginx-proxy container.
Feb 17 00:05:02 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29442]:        - Label the nginx-proxy container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'.
```
I had already passed the `volumes-from` option, but if I explicitly set `NGINX_PROXY_CONTAINER` I get this instead:
```
Feb 17 00:05:51 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29632]: jq: error (at <stdin>:1): Cannot iterate over null (null)
Feb 17 00:05:51 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29632]: Error: can't get docker-gen container id !
Feb 17 00:05:51 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29632]: If you are running a three containers setup, check that you are doing one of the following :
Feb 17 00:05:51 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29632]:        - Set the NGINX_DOCKER_GEN_CONTAINER env var on the letsencrypt-companion container to the name of the docker-gen container.
Feb 17 00:05:51 vps-78bbf645.vps.ovh.us nginx-proxy-acme[29632]:        - Label the docker-gen container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen'
```

I have used both in the past with the same setup though, so I'm not sure what might be different. I am using `podman` and `moby-engine`.

**Comment by heyakyra** [comment] 2023-02-17 01:04
Apparently this is new because Fedora CoreOS switched on `moby-engine` by default https://github.com/coreos/fedora-coreos-tracker/issues/14

I uninstalled that and installed `podman-docker` and ran `sudo systemctl enable --now podman.sock` to get things working again. Leaving this ticket open in case you'd like to handle this edge case in a more elegant way, but feel free to close it.

**Comment by rhansen** [comment] 2023-02-17 07:31
@heyakyra Does nginx-proxy v1.1.0 work with Fedora CoreOS's new default behavior?

**Comment by heyakyra** [comment] 2023-02-22 00:50
Yes, or at least v1.1.0 _ran_ successfully. I didn't actually try getting it to work with a running service without `acme-companion`, and I just switched over from `moby-engine` to `podman-docker`

**Comment by rhansen** [comment] 2023-02-27 01:01
I don't see any suspicious commits between v1.1.0 and v1.2.0.  Can you use `git bisect` to determine which commit broke things?

**Comment by rhansen** [comment] 2023-03-10 09:22
Duplicate of #2189

**Closed by rhansen** 2023-03-10 09:22 UTC

**Comment by rhansen** [comment] 2023-03-10 09:23
The error is similar to #2189, and I think they have the same underlying cause.  That bug has more information, so I'm marking this as a duplicate of that even though this is older.
