### ISSUE TITLE
Docker errors - Nginx keeps looking for files under /etc/nginx/html

### ISSUE THREAD

**Issue by chharish** [nginx-proxy/nginx-proxy#1246] opened 2019-03-14 17:17 UTC
I have a [seperate docker container ](https://github.com/jwilder/nginx-proxy/blob/master/docker-compose-separate-containers.yml) setup with Lesencrypt (using nginx, [nginx-gen](https://github.com/jwilder/docker-gen), [nginx-letsencrypt](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion))

I have the volumes for nginx docker at
```
- /srv/www/nginx-proxy/conf.d:/etc/nginx/conf.d
- /srv/www/nginx-proxy/vhost.d:/etc/nginx/vhost.d
- /srv/www/nginx-proxy/html:/usr/share/nginx/html
- /srv/www/nginx-proxy/certs:/etc/nginx/certs:ro
```

I see a lot of docker errors in nginx docker logs
Most of these errors are caused due to a missing files at /etc/nginx/html 

```
2019-03-14T16:41:41.827406845Z 2019/03/14 16:41:41 [error] 10#10: *29 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 162.220.108.178, server: , request: "GET / HTTP/1.1", host: "54.187.124.124"

2019-03-14T16:41:44.058864267Z 2019/03/14 16:41:44 [error] 10#10: *30 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 83.224.172.148, server: , request: "GET / HTTP/1.1", host: "52.43.94.103:80"

2019-03-14T16:42:49.085729650Z 2019/03/14 16:42:49 [error] 10#10: *37 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 164.52.24.163, server: , request: "GET / HTTP/1.1", host:"54.187.124.124"

2019-03-14T16:47:50.012585507Z 2019/03/14 16:47:50 [error] 10#10: *58 open() "/etc/nginx/html/.well-known/acme-challenge/7mwlZRBfqpmjH1XKH-Qg7B6lyduFU9EPg4QSaTFyT0s" failed (2: No such file or directory), client: 66.133.109.36, server: , request: "GET /.well-known/acme-challenge/7mwlZRBfqpmjH1XKH-Qg7B6lyduFU9EPg4QSaTFyT0s HTTP/1.1", host: "foo.bar"
```

These are the same with other application dockers that are deployed. 

Say we have a [wordpress docker](https://hub.docker.com/_/wordpress/) deployed with volumes 
`- ./wordpress:/var/www/html`

Or say we have a server block setup for external load balancer such as ALB/CloudFront/CloudFlare, this is important for us to mitigate docker errors for these external load balancers to failover to other servers in the event of a server failure.

I see errors for missing files at /etc/nginx/html/ like the below

```
2019-03-14T05:38:06.284529777Z 2019/03/14 05:38:06 [error] 11#11: *689 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 78.162.82.29, server: , request: "GET / HTTP/1.1", host:"alb-aws-com"
2019-03-14T06:57:03.020160983Z 2019/03/14 06:57:03 [error] 11#11: *1011 open() "/etc/nginx/html/wp-config.php" failed (2: No such file or directory), client: 190.188.94.38, server: , request: "GET /wp-config.php HTTP/1.1", host: "54.187.124.124"
2019-03-14T06:57:03.020160983Z 2019/03/14 06:57:03 [error] 11#11: *1011 open() "/etc/nginx/html/wp-config.php" failed (2: No such file or directory), client: 190.188.94.38, server: , request: "GET /wp-config.php HTTP/1.1", host: "54.187.124.124"
2019-03-14T06:57:13.402392385Z 2019/03/14 06:57:13 [error] 11#11: *1011 open() "/etc/nginx/html/wp-admins.php" failed (2: No such file or directory), client: 190.188.94.38, server: , request: "POST /wp-admins.php HTTP/1.1", host: "54.187.124.124"
2019-03-14T06:57:13.402392385Z 2019/03/14 06:57:13 [error] 11#11: *1011 open() "/etc/nginx/html/wp-admins.php" failed (2: No such file or directory), client: 190.188.94.38, server: , request: "POST /wp-admins.php HTTP/1.1", host: "54.187.124.124"
2019-03-14T06:58:20.069384814Z 2019/03/14 06:58:20 [error] 11#11: *1018 open() "/etc/nginx/html/wp-content/plugins/portable-phpmyadmin/wp-pma-mod/index.php" failed (2: No such file or directory), client: 190.188.94.38, server: , request: "GET /wp-content/plugins/portable-phpmyadmin/wp-pma-mod/index.php HTTP/1.1", host: "54.187.124.124"
2019-03-14T06:58:20.069384814Z 2019/03/14 06:58:20 [error] 11#11: *1018 open() "/etc/nginx/html/wp-content/plugins/portable-phpmyadmin/wp-pma-mod/index.php" failed (2: No such file or directory), client: 190.188.94.38, server: , request: "GET /wp-content/plugins/portable-phpmyadmin/wp-pma-mod/index.php HTTP/1.1", host: "54.187.124.124"
2019-03-14T06:58:20.069384814Z 2019/03/14 06:58:20 [error] 11#11: *1018 open() "/etc/nginx/html/wp-content/plugins/portable-phpmyadmin/wp-pma-mod/index.php" failed (2: No such file or directory), client: 190.188.94.38, server: , request: "GET /wp-content/plugins/portable-phpmyadmin/wp-pma-mod/index.php HTTP/1.1", host: "54.187.124.124"
```

Am I missing something or should we consider these errors normal?  Is there a way to get rid of these errors? Please help me out.

**Comment by jonathangaldino** [comment] 2019-05-30 19:29
I'm having the same issue. I'm trying to use nginx-proxy only as a proxy (dã!). However, it's not proxying to my application and it is looking for files under the same path on your error.

**Comment by katticot** [comment] 2020-05-25 09:55
hello i haved the same issue with wordpress and Nginx.

If it can help i just added the port (:80 in my case) to my proxy_pass directive, i dont know why but now it works.
if someone can tell me why it would be great !

location / {
      proxy_pass http://server:port;
  }
instead of

location / {
      proxy_pass http://server;
  }

**Comment by PauloBoaventura** [comment] 2020-09-16 19:55
what's new?

**Comment by sysnasri** [comment] 2021-08-22 11:04
same issue on kubernetes

**Comment by aschuhardt** [comment] 2021-08-31 21:34
what do we do about this?

**Comment by buchdag** [comment] 2021-09-01 06:56
This issue is pretty vague and old, feel free to reopen if you experience it and have tangible way to reproduce it, closing for now.

**Closed by buchdag** 2021-09-01 06:56 UTC

**Comment by JStet** [comment] 2022-07-30 10:40
I am experiencing the same issue. 

My docker compose:

``` 
version: "3.8"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html  
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    networks:
      - proxy


  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME={{ MONGO_INITDB_ROOT_USERNAME }}
      - MONGO_INITDB_ROOT_PASSWORD={{  MONGO_INITDB_ROOT_PASSWORD  }}
    volumes:
      - mongodb-data:/data/db
    networks:
      - db
    restart: unless-stopped 


  cherrypy:
    build: ../app/.
    container_name: cherrypy
    environment:
      - MONGODB_URI={{  MONGODB_URI  }}
      - PORT=80
      - LOCAL=False
      - USERNAME={{  USERNAME  }}
      - PASSWORD={{  PASSWORD  }}
      - LETSENCRYPT_HOST={{ SURVEY_DOMAIN }}
      - VIRTUAL_HOST={{ SURVEY_DOMAIN }}
      - VIRTUAL_PORT=80
    ports:
      - 80
    depends_on:
      - nginx-proxy
    networks:
      - proxy
      - db
    restart: unless-stopped 
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports: 
      - 9090
    volumes:
      - prometheus-data:/prometheus 
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'   
    networks:
      - monitoring
    restart: unless-stopped 
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100
    networks:
      - monitoring
    restart: unless-stopped 

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    command:                                                                                                          
    - -nginx.scrape-uri                                                                                               
    - http://nginx-proxy/nginx_status   
    ports:
      - 9113
    networks:
      - monitoring
    restart: unless-stopped 


  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
      - nginx-proxy
    ports:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - proxy
      - monitoring
    environment:
      - LETSENCRYPT_HOST={{ MONITORING_DOMAIN }}
      - VIRTUAL_HOST={{ MONITORING_DOMAIN }}
      - VIRTUAL_PORT=3000
    restart: unless-stopped  
  

networks:
  proxy:
    name: proxy
  db:
    name: db
  monitoring:
    name: monitoring

volumes:
  certs: {}
  vhost: {}
  html: {}
  acme: {}
  mongodb-data: {}
  prometheus-data: {}
  grafana_data: {}
  volumes:
    certs: {}
    vhost: {}
    html: {}
    acme: {}
    mongodb-data: {}
    prometheus-data: {}
    grafana_data: {}
```

**Comment by mickaelperrin** [comment] 2022-09-28 21:51
This issue appears when : 
- error_log is enable in the template 
- and we try to reach a non existent ressource in a proxified service.

It looks like it is generated because there is no root directive in the server blocks.
root defaults to `/etc/nginx/html` which is a  non existent path which is causing the error storm in logs.

**Comment by richardARPANET** [comment] 2023-02-26 18:11
For me the issue was within the container, within `/usr/share/nginx/html` dir, `index.html` was missing.

**Comment by buchdag** [comment] 2023-02-28 07:23
@jstet you're using the `LETSENCRYPT_HOST` environment variable but I don't see any acme-companion container in your compose file.

**Comment by buchdag** [comment] 2023-02-28 07:26
@mickaelperrin @richardARPANET ciould you post the configuration generated by nginx-proxy in those cases ?

**Comment by aanoaa** [comment] 2024-09-19 23:14
In my case, I used the [access_log](https://nginx.org/en/docs/http/ngx_http_log_module.html#access_log) directive in the `default_location`, which caused the same error.
It was a configuration to log daily.

```
    if ($time_iso8601 ~ "^(\d{4})-(\d{2})-(\d{2})") {
        set $year $1;
        set $month $2;
        set $day $3;

        access_log /var/log/nginx/access.$year-$month-$day.log vhost;
    }
```

```
    nginx.1     | 2024/09/19 22:47:59 [error] 37#37: *1 testing "/etc/nginx/html" existence failed (2: No such file or directory) while logging request, client: 10.255.1.1, server: example.com, request: "GET / HTTP/1.1", upstream: "http://10.255.1.3:80/", host: "foo.example.com"
```

When the access_log directive is used, it checks the [root](https://nginx.org/en/docs/http/ngx_http_core_module.html#root) directive. Since the generated server block did not have a root directive, it referred to the default (`/etc/nginx/html`), but that directory did not exist.

> during each log write the existence of the request’s root directory is checked, and if it does not exist the log is not created. It is thus a good idea to specify both root and access_log on the same configuration level:
>
> <https://nginx.org/en/docs/http/ngx_http_log_module.html#access_log>

So, I created the `/etc/nginx/html` directory, and the issue was resolved.
