### ISSUE TITLE
Error response from daemon: driver failed programming external connectivity on endpoint nginx-proxy (669659d666e6b6164716c6009cc1f1b413f2130e8d6238db341769bce23620fa): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE) Error: failed to start containers: nginx-proxy

### ISSUE THREAD

**Issue by xiexiangnow** [nginx-proxy/nginx-proxy#839] opened 2017-05-31 07:18 UTC
Error response from daemon: driver failed programming external connectivity on endpoint nginx-proxy (669659d666e6b6164716c6009cc1f1b413f2130e8d6238db341769bce23620fa): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
Error: failed to start containers: nginx-proxy

need help~~

**Comment by g13013** [comment] 2017-05-31 11:33
had the same error, this fixed the problem but it's kinda annoying

https://github.com/docker/compose/issues/3277#issuecomment-243353309

**Comment by zipzit** [comment] 2017-07-06 05:04
Ouch. That went from bad to worse. I tried the fix mentioned by @g13013, but I ended up generating a whole bunch of new errors... 

initial error
`ERROR: for nginx-proxy  Cannot start service nginx-proxy: driver failed programming external connectivity on endpoint nginx-proxy (d56e2f1833058f7e6141d0d56d8ef1b675785db40ec147e445172763d4240a02): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use`
`ERROR: Encountered errors while bringing up the project.`

did the tests from the link above:
`docker rm -f $(docker ps -aq) (will remove all of your containers)`
`docker network rm $(docker network ls -q) (will remove all of your networks)`
`docker run --rm -v /var/lib/docker/network/files:/network busybox rm /network/local-kv.db`

and now I end up with 
`Starting root_dfd_db_1`
`Starting root_rc_web_1`
`Starting root_aim_db_1`
`Starting root_iwerk_db_1`
`Starting root_phpmyadmin_1`
`Starting nginx-proxy`
`ERROR: for dfd_db  Cannot start service dfd_db: failed to update store for object type *libnetwork.endpointCnt: Key not found in store`
`ERROR: for rc_web  Cannot start service rc_web: failed to update store for object type *libnetwork.endpointCnt: Key not found in store`
`ERROR: for aim_db  Cannot start service aim_db: failed to update store for object type *libnetwork.endpointCnt: Key not found in store`
`ERROR: for phpmyadmin  Cannot start service phpmyadmin: failed to update store for object type *libnetwork.endpointCnt: Key not found in store`
`ERROR: for iwerk_db  Cannot start service iwerk_db: failed to update store for object type *libnetwork.endpointCnt: Key not found in store`
`ERROR: for nginx-proxy  Cannot start service nginx-proxy: failed to update store for object type *libnetwork.endpointCnt: Key not found in store`
`ERROR: Encountered errors while bringing up the project.`

I'm working in a Virtual Private Server over at Vultr.. I think I'll just delete the entire repository and start again...

for reference:   `$ docker -v`
`Docker version 17.06.0-ce, build 02c1d87`
`$ docker-compose -v`
`docker-compose version 1.8.0, build unknown`

**Comment by zipzit** [comment] 2017-07-06 06:15
Update.  So that was a total fail.  I opened new server.  Installed fail2ban with firewall.  Then installed docker-ce and docker-compose.  Ran my docker-compose file (which I've tested previously on different OS without fail2ban installed) and things ran fine there.    I immediately get the  `listen tcp 0.0.0.0:80: bind: address already in use` error upon first time `$ docker-compose up -d` statement.

I'd skip the fail2ban stuff, but I can see I'm getting thousands of probes on port 22 / per hour.. 

VPS: Ubuntu 17.04, 1Gb Ram, Single Processor
Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.14.0-rc2, build 24dae73

My site is nothing crazy.  Three wordpress sites (image: wordpress:latest), three mysql DB's (image: mariadb), one static site ( image: taka0225/alpine-http-server:latest, with expose - 8080), phpmyadmin (image: phpmyadmin/phpmyadmin:latest) and everything on port 80 controlled via image: jwilder/nginx-proxy

The conflict must be coming from either ubuntu 17.04 or fail2ban stuff?     Still testing..

**Comment by mplacona** [comment] 2017-09-22 16:11
Pretty late I know, but I solved this issue by running the following:

```
docker stop $(docker ps -a -q); docker rm $(docker ps -a -q); docker volume rm $(docker volume ls -qf dangling=true)

docker network rm $(docker network ls -q)

sudo lsof -nP | grep LISTEN

sudo kill -9 1548
```
Where on the last line, 1548 was a service that was using port 80 as returned by the penultimate line.

Hope this helps you out.

**Comment by anugrah-atreya** [comment] 2017-09-29 15:31
i had same problem because IIS was already running on my port 80. I stopped IIS and then executed the nginx run command. Everything worked smooth.

**Comment by stphane** [comment] 2017-10-06 08:19
mplacona is right, using Ubuntu 16.04, port 80 was already in use by another process.
```
$ sudo lsof -nP | grep LISTEN
apache2    2153                   root    4u     IPv6              29122       0t0        TCP *:80 (LISTEN)
apache2    7645          www-data    4u     IPv6              29122       0t0        TCP *:80 (LISTEN)
…
```
Has you can see apache2 is guilty. Since I'm not using it at all, I decided to turn off automatic launch on startup.
```
$ sudo systemctl stop apache2
echo manual | sudo tee /etc/init/apache2.override
```

**Comment by rickcosme** [comment] 2017-11-30 00:45
You need to kill the processes running on port 80
To list what's running...
`$sudo lsof -i :80
httpd   422 root    5u  IPv6 0x7...     0t0  TCP *:http (LISTEN)
httpd   425 _www    5u  IPv6 0x7...     0t0  TCP *:http (LISTEN)`

Perform the following to stop it.
`$sudo apachectl stop`

Worked for me. I was able to run `docker run -d -p 80:80 --name webserver nginx`

**Comment by prasadram** [comment] 2018-01-01 08:53
i am also facing similar issue, i have checked there is no process running on that port

**Comment by Aswad1979** [comment] 2018-02-26 18:59
Thank you mplacona.

**Comment by IGZmanuelMartinVivaldi** [comment] 2018-04-20 15:02
To solve the following error in Windows: just Restart Docker (from tray menu or selecting the 'Restart Docker...' option in Settings/Reset)

`Cannot start service YOUR_SERVICE: driver failed programming external connectivity on endpoint ...`

**Comment by rvdbogerd** [comment] 2018-05-16 14:46
Had the same problem, when running all of @mplacona 's commands, I found that suddenly I have apache running on my ubuntu machine. No idea why, but killing the apache server (through `sudo apachectl stop`) seemed to fix my problem.

**Comment by PremiumLearnings** [comment] 2018-11-14 10:11
I was also facing the same problem but after a long time a meet with the perfect solution

1. type docker container ls -a (check the container which is using that port number )
2. docker container rm -f (Deallocate the port by removing that container)
3. Assing your new container with your port number

**Comment by Diwakar-time** [comment] 2018-12-05 05:14
We need to find our the running container which is occupying that port 
command-> $ docker container ls   
it will list out running container, then pick the container with docker id and 
stop running container by using $docker container stop <CONTAINER ID>
![image](https://user-images.githubusercontent.com/13012962/49491578-c6cfb600-f87a-11e8-9c25-7c478d8add0b.png)

**Comment by jasperboyd** [comment] 2019-02-09 18:05
If you're on macOs you probably have apache running on port 80, that was my problem:

`sudo apachectl stop`

**Comment by flyq** [comment] 2020-12-29 09:43
```shell
sudo lsof -nP | grep LISTEN
```
see the port

**Comment by brevvi** [comment] 2021-03-16 20:51
> Pretty late I know, but I solved this issue by running the following:
> 
> ```
> docker stop $(docker ps -a -q); docker rm $(docker ps -a -q); docker volume rm $(docker volume ls -qf dangling=true)
> 
> docker network rm $(docker network ls -q)
> 
> sudo lsof -nP | grep LISTEN
> 
> sudo kill -9 1548
> ```
> 
> Where on the last line, 1548 was a service that was using port 80 as returned by the penultimate line.
> 
> Hope this helps you out.

It works for me!

**Comment by buchdag** [comment] 2021-08-02 13:57
This isn't an issue caused by the container itself, closing.

**Closed by buchdag** 2021-08-02 13:57 UTC

**Comment by adilsarsembin** [comment] 2023-04-05 06:29
Check if you have running apps on certain port. I had my FastAPI hosted on localhost, that's why he couldn't connect.
