### ISSUE TITLE
Unable to access google fourm

### ISSUE THREAD

**Issue by BoxOfCereal** [nginx-proxy/nginx-proxy#1502] opened 2020-09-29 07:30 UTC
I am trying to access the google groups but get :
`Content unavailable Double-check the link, or try switching accounts`

**Comment by tkw1536** [comment] 2020-09-30 21:28
Duplicate of #1378.

**Closed** 2021-04-26 13:02 UTC

**Comment by buchdag** [comment] 2021-06-20 16:14
We're now using [GitHub Discussions](https://github.com/nginx-proxy/nginx-proxy/discussions).
