### ISSUE TITLE
Working on a Multi-node cluster?

### ISSUE THREAD

**Issue by andreykats** [nginx-proxy/nginx-proxy#595] opened 2016-10-06 00:31 UTC
Is it possible to use jwilder/nginx-proxy on a cluster?

I currently have a multi node AWS ECS cluster and jwilder/nginx-proxy does not appear to see containers that are running on a different node of the same cluster. 

Any input is appreciated.

**Comment by pascalandy** [comment] 2016-10-09 22:33
I guess you are talking about running under an orchestration system like Docker Swarm ?

Check this out: https://github.com/jwilder/nginx-proxy/issues/520

**Comment by tkw1536** [comment] 2022-04-10 17:05
Duplicate of #97

**Closed by tkw1536** 2022-04-10 17:05 UTC
Labels: status/duplicate
