### ISSUE TITLE
Upgrade to latest on 2021.04.12 broke upstream generation

### ISSUE THREAD

**Issue by ingwinlu** [nginx-proxy/nginx-proxy#1586] opened 2021-04-12 04:02 UTC
Just upgraded to latest (from the latest of approx last week).
Now the reverse proxy template seems to no longer generated correctly. After a quick inspection I see nginx -s reload is fired and failing. Inspection of the conf.d/default file reveals that the upstream sections are no longer populated at all.

```
# heroicdebugging.biz                                                                                                  
upstream heroicdebugging.biz {                                                                                         
}                                                                                                                      
server {                                                                                                               
        server_name heroicdebugging.biz;                                                                               
        listen 80 ;                                                                                                    
        access_log /var/log/nginx/access.log vhost;                                                                    
        # Do not HTTPS redirect Let'sEncrypt ACME challenge                                                            
        location ^~ /.well-known/acme-challenge/ {                                                                     
                auth_basic off;                                                                                        
                auth_request off;                                                                                      
                allow all;                                                                                             
                root /usr/share/nginx/html;                                                                            
                try_files $uri =404;                                                                                   
                break;                                                                                                 
        }                                                                                                              
        location / {                                                                                                   
                return 301 https://$host$request_uri;                                                                  
        }                                                                                                              
}

server {                                                                                                               
        server_name heroicdebugging.biz;                                                                               
        listen 443 ssl http2 ;                                                                                         
        access_log /var/log/nginx/access.log vhost;                                                                    
        ssl_session_timeout 5m;                                                                                        
        ssl_session_cache shared:SSL:50m;                                                                              
        ssl_session_tickets off;                                                                                       
        ssl_certificate /etc/nginx/certs/heroicdebugging.biz.crt;                                                      
        ssl_certificate_key /etc/nginx/certs/heroicdebugging.biz.key;                                                  
        ssl_dhparam /etc/nginx/certs/heroicdebugging.biz.dhparam.pem;                                                  
        ssl_stapling on;                                                                                               
        ssl_stapling_verify on;                                                                                        
        ssl_trusted_certificate /etc/nginx/certs/heroicdebugging.biz.chain.pem;                                        
        add_header Strict-Transport-Security "max-age=31536000" always;                                                
        include /etc/nginx/vhost.d/heroicdebugging.biz;                                                                
        location / {                                                                                                   
                proxy_pass http://heroicdebugging.biz;                                                                 
        }                                                                                          
} 
```

Any ideas?

//EDIT:
Currently looking if maybe the docker update to 20.10.5 is to blame as I don't see any changes in the repo that should affect generation.
// EDIT2: 
Manually filling in the server blocks restored connectivity

**Comment by megamaced** [comment] 2021-04-12 07:36
i have this problem too
dockergen.1 | 2021/04/12 07:29:46 Received event start for container 908f275fb223
dockergen.1 | 2021/04/12 07:29:46 Generated '/etc/nginx/conf.d/default.conf' from 8 containers
dockergen.1 | 2021/04/12 07:29:46 Error running notify command: nginx -s reload, exit status 1

openSUSE Tumbleweed, Docker 20.10.5_ce-1.2, nginx-proxy:latest (4 days ago)

**Comment by megamaced** [comment] 2021-04-12 07:43
OK so it doesn't look like a problem with nginx-proxy. I rolled back my system with `snapper rollback` and now it works again using the latest nginx-proxy:latest (4 days ago)

There was no docker update done. Strange, looks like openSUSE broke something. One of these package updates is to blame:

`zypper list-updates 
Loading repository data...
Reading installed packages...
S | Repository              | Name                      | Current Version   | Available Version | Arch
--+-------------------------+---------------------------+-------------------+-------------------+-------
v | openSUSE-Tumbleweed-Oss | MicroOS-release           | 20210330-929.1    | 20210408-933.1    | x86_64
v | openSUSE-Tumbleweed-Oss | MicroOS-release-appliance | 20210330-929.1    | 20210408-933.1    | x86_64
v | openSUSE-Tumbleweed-Oss | attr                      | 2.4.48-3.23       | 2.5.1-1.1         | x86_64
v | openSUSE-Tumbleweed-Oss | curl                      | 7.75.0-1.1        | 7.76.0-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | fcoe-utils                | 1.0.33-3.4        | 1.0.34-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | git                       | 2.30.2-1.1        | 2.31.1-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | git-core                  | 2.30.2-1.1        | 2.31.1-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | kernel-default            | 5.11.6-1.4        | 5.11.11-1.2       | x86_64
v | openSUSE-Tumbleweed-Oss | libattr1                  | 2.4.48-3.23       | 2.5.1-1.1         | x86_64
v | openSUSE-Tumbleweed-Oss | libcap2                   | 2.48-1.4          | 2.49-1.1          | x86_64
v | openSUSE-Tumbleweed-Oss | libcurl4                  | 7.75.0-1.1        | 7.76.0-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | libfreebl3                | 3.61-1.2          | 3.62-1.1          | x86_64
v | openSUSE-Tumbleweed-Oss | libgnutls30               | 3.7.1-1.1         | 3.7.1-1.2         | x86_64
v | openSUSE-Tumbleweed-Oss | libgpg-error0             | 1.41-1.3          | 1.42-1.1          | x86_64
v | openSUSE-Tumbleweed-Oss | libgpgme11                | 1.15.1-1.3        | 1.15.1-2.1        | x86_64
v | openSUSE-Tumbleweed-Oss | libldb2                   | 2.2.0-2.5         | 2.2.1-1.1         | x86_64
v | openSUSE-Tumbleweed-Oss | libncurses6               | 6.2.20210313-16.1 | 6.2.20210327-17.1 | x86_64
v | openSUSE-Tumbleweed-Oss | libopenssl1_1             | 1.1.1j-2.1        | 1.1.1k-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | libprocps8                | 3.3.17-3.1        | 3.3.17-4.1        | x86_64
v | openSUSE-Tumbleweed-Oss | libsystemd0               | 246.11-1.1        | 246.13-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | libudev1                  | 246.11-1.1        | 246.13-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | makedumpfile              | 1.6.7-4.5         | 1.6.8-1.1         | x86_64
v | openSUSE-Tumbleweed-Oss | ncurses-utils             | 6.2.20210313-16.1 | 6.2.20210327-17.1 | x86_64
v | openSUSE-Tumbleweed-Oss | openssl                   | 1.1.1j-1.1        | 1.1.1k-1.1        | noarch
v | openSUSE-Tumbleweed-Oss | openssl-1_1               | 1.1.1j-2.1        | 1.1.1k-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | procps                    | 3.3.17-3.1        | 3.3.17-4.1        | x86_64
v | openSUSE-Tumbleweed-Oss | python3-ldb               | 2.2.0-2.5         | 2.2.1-1.1         | x86_64
v | openSUSE-Tumbleweed-Oss | systemd                   | 246.11-1.1        | 246.13-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | systemd-logger            | 246.11-1.1        | 246.13-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | systemd-sysvinit          | 246.11-1.1        | 246.13-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | terminfo                  | 6.2.20210313-16.1 | 6.2.20210327-17.1 | x86_64
v | openSUSE-Tumbleweed-Oss | terminfo-base             | 6.2.20210313-16.1 | 6.2.20210327-17.1 | x86_64
v | openSUSE-Tumbleweed-Oss | udev                      | 246.11-1.1        | 246.13-1.1        | x86_64
v | openSUSE-Tumbleweed-Oss | vim                       | 8.2.2607-1.2      | 8.2.2725-1.1      | x86_64
v | openSUSE-Tumbleweed-Oss | vim-data-common           | 8.2.2607-1.2      | 8.2.2725-1.1      | noarch
v | openSUSE-Tumbleweed-Oss | vim-small                 | 8.2.2607-1.2      | 8.2.2725-1.1      | x86_64`

**Comment by buchdag** [comment] 2021-04-12 08:09
@megamaced @ingwinlu could you post the result of the following commands with the non working container?

```
docker inspect yournginxproxycontainer
docker exec yournginxproxycontainer cat /proc/1/cpuset
docker exec yournginxproxycontainer cat /proc/self/cgroup
docker exec yournginxproxycontainer cat /proc/self/mountinfo
```

Related docker-gen issues and PR :


https://github.com/jwilder/docker-gen/pull/335
https://github.com/jwilder/docker-gen/pull/336
https://github.com/jwilder/docker-gen/pull/344
https://github.com/jwilder/docker-gen/pull/345

**Comment by ingwinlu** [comment] 2021-04-12 08:29
This looks like the same issue that you linked. I worked around it by filling in the sever fields manually and for good measure chmod 400 on it so docker-gen can not destroy it again.

I don't think I can add any debug information compared to what is already in all the linked threads. Any ETA on merging the updated docker-gen into this repo?

**Comment by buchdag** [comment] 2021-04-12 08:35
> Any ETA on merging the updated docker-gen into this repo?

See #1585 : as soon as https://github.com/jwilder/docker-gen/pull/345 has been merged and tagged version with this fix is available

**Comment by ingwinlu** [comment] 2021-04-12 11:28
just wondering if the proposed fix would really help me, seeing as in my case /proc/1/cpuset does not container the containerid

**Comment by buchdag** [comment] 2021-04-12 11:41
The PR I linked to is mostly meant to fix a regression in jwilder/docker-gen#336 by adding a fallback method.

As stated in #1585, **docker-gen** `0.7.5` might fix your issue but break **nginx-proxy** for other people.

**Comment by buchdag** [comment] 2021-04-12 21:07
@ingwinlu could you try `nginxproxy/nginx-proxy:1586` ?

**Comment by ingwinlu** [comment] 2021-04-13 03:30
> @ingwinlu could you try `nginxproxy/nginx-proxy:1586` ?

works like a charm:
```
# heroicdebugging.biz
upstream heroicdebugging.biz {
                                ## Can be connected with "bridge" network
                        # nginx_www
                        server 172.17.0.3:80;
}
```

**Comment by buchdag** [comment] 2021-04-13 11:20
@megamaced does nginxproxy/nginx-proxy:1586 works for you too ?

**Comment by megamaced** [comment] 2021-04-14 07:03
> @megamaced does `nginxproxy/nginx-proxy:1586` works for you too ?

@buchdag yeah seems to work great after updating my system again

Thanks

**Comment by othbert** [comment] 2021-04-24 18:40
Chiming in with another success for `nginxproxy/nginx-proxy:1586 ` and also on openSUSE tumbleweed. Been going back and forth between snapshots and apparmor trying to find a cause until noticing there were more dockergen errors than usual and that it wasn't even seeing the upstream containers 🤦🏼
Still not exactly sure what the root of the break in openSUSE is, but narrowed down the release to the switch from 20210406 to 20210408 (for me at least)

**Comment by dmp1ce** [comment] 2021-04-26 11:06
My services have been running for years without a problem. I was on the old `jwilder/nginx-proxy` image from github. No upstream generation also occurred for me today. Updating to `nginxproxy/nginx-proxy:1586` fixed it!

**Closed** 2021-04-26 13:09 UTC
Labels: kind/bug
