### ISSUE TITLE
Proxy/Companion/Docker-Gen not working after reboot/restart of Docker daemon

### ISSUE THREAD

**Issue by Gaibhne** [nginx-proxy/nginx-proxy#1696] opened 2021-07-05 10:07 UTC
We use `latest` for everything from this repo, but I have noticed this behaviour in the past, so it's not a regression.

I have witnessed the problem on two different machines:

```
Docker version 20.10.7, build f0df350
Docker version 20.10.6, build 370c289
```

We use the three container Docker Compose solution described in the documentation.

Bug description
-----------------

When the server (or the Docker daemon) is restarted, then while all containers come up correctly, many, sometimes all 'external' containers are not proxied to correctly. To be clear, I am talking about third party containers that 'request' proxying through this repos services by having the appropriate environment variables set. Restarting this repos containers, and then restarting the problematic containers afterwards, results in correct proxying, so I suspect that the problem is that the order in which containers are starting back up.

acme-companion image version
-----------------

```
Info: running acme-companion version v2.1.0-16-g027c3cf
```

nginx-proxy configuration
-----------------

We cloned this repo at 027c3cf3

The other containers are a variety of different services, none of which configurations would matter, I would expect, as they all have different configs and all suffer from the same problem. As there are about ~80 different ones, unless there is anything specific, I'd rather not spend a few hours sanitizing and posting the different configs ;)

Docker host
-----------------

 - OS: CentOS 8, Raspbian GNU/Linux 10 (buster)
 - Docker version 20.10.7, build f0df350, Docker version 20.10.6, build 370c289

**Comment by buchdag** [comment] 2021-07-14 19:30
@Gaibhne I transferred the issue because nginxproxy/acme-companion does not do anything related to the actual proxying, so the problem is most probably with nginxproxy/nginx-proxy.

**Comment by Gaibhne** [comment] 2021-08-04 11:50
@buchdag what additional info is needed ?

**Comment by buchdag** [comment] 2021-08-04 15:14
@Gaibhne I'll need at least

- your nginx-proxy configuration (compose file, commande line, etc).
- the version of `nginxproxy/nginx-proxy` you're using (or the version of `nginxproxy/docker-gen` and the `nginx.tmpl` file you are using if it's a separate containers setup).
- the results of:

```console
docker logs yournginxproxycontainer
```
 
 and
 
```console
docker exec yournginxproxycontainer nginx  -T
```

both when your proxied containers are in a non working state after a reboot and when they're back in a working state.

**Comment by buchdag** [comment] 2023-12-20 09:45
No answer from issue creator.

**Closed by buchdag** 2023-12-20 09:45 UTC
Labels: status/needs-more-info
