### ISSUE TITLE
Unable to get basic SSL working 

### ISSUE THREAD

**Issue by swoopdk** [nginx-proxy/nginx-proxy#366] opened 2016-02-17 11:32 UTC
I have been struggeling for two days with getting SSL support working. 

My procedure is as follows:

I have run my docker container with the following env variables. 
VIRTUAL_HOST=test.example.com
VIRTUAL_PORT=443
VIRTUAL_PROTO=https

When i first try to connect to my docker host (docker01.example.com) using the randomly docker assigned SSL port my container works. I can log in and everything. I should note that the container has my SSL certs mounted itself for the app it's running to be working. 

Now i would like to setup the proxy to be a step in front, to avoid having to type "docker01.example.com:randomport" everytime. Plus of course the port changes. 
So i would like for test.example.com to be my containers adress. 
1.  I run the nginx proxy with SSL support pr the instructions like this
   docker run -d -p 80:80 -p 443:443 --name proxy2 -v /root/docker/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy

Anything i'm missing ?

The port 80 redirect is working. That means i can get to my site via non SSL using test.example.com  but with HTTPS i get a chrome error of "This webpage is not available
ERR_CONNECTION_CLOSED"

I'm a little at a loss.

**Comment by swoopdk** [comment] 2016-02-17 12:45
Update

This is from my default.conf file in the proxy container

```
upstream test.example.com  {
		# test.example.com
		server 172.17.0.5;
}
server {
	server_name test.example.com ;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass https://test.example.com;
	}
}
```


So from my limited (almost none) exprience i can conclude that i'm missing the listen 443, and some information about the certs. But i don't know why as they are mounted pr the instructions and the rest should come automatically ? My container exposes port 443 so I dont see why it shouldnt work :(

**Comment by bibby** [comment] 2016-02-17 21:08
(some observations, may or may not be helpful)
What strikes me as odd is that there is no port after the container IP  in the upstream definition. It just doesn't seem to fit any of the three code paths in the [template](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L10). The template is [confirmed used](https://github.com/jwilder/nginx-proxy/blob/master/Procfile#L2) on a fresh pull during local testing. The port is always included in my tests.

Are you certain you've pulled a recent image?

One thing gleamed from viewing these templates is that `VIRTUAL_PORT` is only inspected when more than one port is exposed in your container. When only one exists, it is used.

quick steps attempting to reproduce:

    docker pull jwilder/nginx-proxy
    # a vanilla nginx will do
    docker run -d -e VIRTUAL_HOST=foo.bar -e VIRTUAL_PORT=443 -e VIRTUAL_PROTO=https nginx
    docker run -d --name proxy -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
    docker exec -it proxy cat /etc/nginx/conf.d/default.conf

The result includes a port as expected.

    upstream foo.bar {
        # gloomy_jennings
        server 172.17.0.2:443;
    }

**Comment by swoopdk** [comment] 2016-02-18 07:46
I might have trimmed the port number because i specifically remember seeing it. 

BUT i have maybe found out the problem Seems when i try to do the env variables in an --env-file somehow it doesnt get picked up :( 

I will update later today with my findings.

**Comment by swoopdk** [comment] 2016-02-18 13:54
I have now have it running, but can it be true i cannot include the VIRTUAL_HOST, VIRTUAL_PORT and VIRTUAL_PROTO in an env-file and just reference them with --env-file=myenvfile.env

?

**Comment by ganehag** [comment] 2016-02-18 17:50
Using docker 1.10.1 i have no problem importing a range of env variables into a container using --env-file=a_range.env. As well as having nginx-proxy grab my containers using an env-file for each of the containers.

Run inspect on the app container and see if the variables are set.
> docker inspect --format '{{ index (index .Config.Env) }}' my_container

If not, it is not an issue with nginx-proxy but with your env file - or docker. Or you are overriding the env.file using '-e' arguments.

**Comment by swoopdk** [comment] 2016-02-19 11:08
I have issue with this. The env gets set just fine from what i can see using the env-file (all other env variables are there including the VIRTUAL ones. However i made the same container with both the env file and with -e. Only the -e works. 

kiksekage is with env-file and kiksekage2 is with -e. 

```
server {
	server_name kiksekage.example.com ;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass https://kiksekage.example.com;
	}
}
upstream kiksekage2.example.com {
			# angry_swanson
			server 172.17.0.6:443;
}
server {
	server_name kiksekage2.example.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name kiksekage2.example.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_certificate /etc/nginx/certs/example.com.crt;
	ssl_certificate_key /etc/nginx/certs/example.com.key;
	add_header Strict-Transport-Security "max-age=31536000";
	location / {
		proxy_pass https://kiksekage2.example.com;
	}
}
```

I have replaced our actual domain info with example.com, but the example shows i cannot get the nginx to catch the kiksekage.example.com with the env-file. Or at least not with SSL somehow. Only HTTP.

Any ideas ?

docker -v
Docker version 1.9.1, build a34a1d5

**Comment by ganehag** [comment] 2016-02-19 12:57
Just to establish what you want to achieve. So that I understand the situation.

You have 1.. X containers with web servers listening on 443 with proper SSL certificates. These SSL certs are inside each container. Now you wish to proxy all of these through a single web server. You wish to use HTTPS between the proxy and upstream servers.

Questions:
1. Are you 100% sure the certificate files exists? So that docker-gen knows that is should generate the correct server segment.
2. Are the certificates stored on the host or in the containers.
3. Do the certificate files exists for both/all domains.
4. In the config above kiksekage2.example.com uses a wildcard/SNI certificate I suppose. Since the cert files are example.com.{key,crt}. Are you using CERT_NAME=example.com for both containers?
5. Or are you using symlinks with from kiksekage2.example.com.{key,crt} to example.com.{key,crt}. If so, are the links working? Take note the symlinks also should resolve inside nginx-proxy to the certificate files in question.

> kiksekage2.example.com.key -> /srv/my/stuff/example.com.key

Is right from outside Docker. But inside the container the link is broken. Use relative links in this case.

**Comment by swoopdk** [comment] 2016-02-19 13:09
First off you are correct. I have a webapp that runs in a container. It don't want to expose it as such but rather than the proxy handle incomming traffic. That way i don't have to worry about port numbers ect. 
Yes the container has SSL and works on its own. The SSL certificates for the endpoint there is mounted from the host and works for the app itself if i expose it's ports. 

1. The certificate files exist. I want to use a wildcard certificate. It works for kiksekage2 but not for kiksekage and both ahve the same domain. So wildcard certs should work ? also works on my current running version with -e but not with the same variables in an env file. 

2. The certicates are stored on the host and referenced by a mounted volume.  I have double checked they are able to be found from inside the nginx container. Tried both with symlinks, copies and various naming schemes. I would prefer to use the wildcard naming scheme rather than making seperate ones all the time. 

3. Yes. It's a wildcard certificate for an a domain like *.example.com

4. I have not used CERT_NAME in either example. The only difference in the two (kiksekage and kiksekage2) are that i include the ENV variables from -e or from a file with --env-file= and of course the differences in names. 

5. No symlinks at the moment. I have mounted the certificates folder from the proxy container and everything is listed there no problem. 


I tried to be very specific and create kiksekage and the the exact same container but calling the ENV variables from the env-file instead of from -e.

**Comment by ganehag** [comment] 2016-02-19 13:37
Right, the main problem here is not the templates or anything like that. It is, that for some reason your env-files does not work inside the template, but -e does.

My first though now is that you are using a local domain with .pem,.crt,.key or something similar that breaks the template. But since it works for you with -e the only remaining thing that comes to mind is that the file is broken. Does any version for any domain of your env-files work? Have you tried to trash them and remake them. Or hexdump the env files and ensure they only contain valid characters.

**Comment by swoopdk** [comment] 2016-02-22 08:43
I have not tried that yet. I will see if i can find time to re-make some fresh env files, but i doubt it since all variables are being read into the container. Including the VIRTUAL ones, so the container clearly gets everything from the env-file.

**Comment by sallespro** [comment] 2016-02-24 06:01
Eventhoug i can see the variables in the container:
`$ docker inspect --format '{{ index (index .Config.Env) }}' whoami
[VIRTUAL_HOST=mydomain.com VIRTUAL_PROTO=https VIRTUAL_PORT=443 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PORT=8000]
`
i get `502 Bad Gateway` running

```
docker run -e VIRTUAL_HOST=mydomain.com -e VIRTUAL_PROTO=https -e VIRTUAL_PORT=443 -p 8000:8000 --name whoami -t jwilder/whoami
```

**Comment by patsissons** [comment] 2016-02-25 03:51
I had a lot of trouble with getting SSL set up. My issue ended up being that the container was not listening on `443`. Once I found this issue I inspected the `default.conf` file and confirmed that 443 was not active. Once I restarted the container the conf file was updated and `443` was active and everything started to work.

Lesson: get your keys in place *BEFORE* you start your (proxied) container, otherwise the keys won't get picked up by the proxy container to update the conf file.

**Comment by egorvas** [comment] 2016-06-27 07:58
Hi Ive a very similar issue, will be glad if will help me

How I start my nginx-proxy container:

`sudo docker run -d -p 80:80 -p 443:443 -v /home/user/crt:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

How I start my parse server container:

 `sudo docker run -d -e APP_ID=id -e MASTER_KEY=password -e VIRTUAL_PORT=1337 -e VIRTUAL_PROTO=https -e VIRTUAL_HOST=test.domain.com  -p 1337:1337  --link mongo --name parse-server yongjhih/parse-server`

How my nginx config looks like:

`# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
upstream test.domain.com {
				## Can be connect with "bridge" network
			# parse-server
			server 172.17.0.5:1337;
}
server {
	server_name test.domain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name test.domain.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ECDHE-RSA-AES128-GCM......
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_certificate /etc/nginx/certs/domain.com.crt;
	ssl_certificate_key /etc/nginx/certs/domain.com.key;
	add_header Strict-Transport-Security "max-age=31536000";
	location / {
		proxy_pass https://test.domain.com;
	}
}`

What I able to see: `502 Bad Gateway error`

What I would like to see : `Working parse server`

Note: `I already tried different configuration of ports, like VIRTUAL_PORT=443  instead of VIRTUAL_PORT=1337 and etc`

**Comment by wader** [comment] 2016-06-27 09:16
@egorvas does it work if you skip setting `VIRTUAL_PORT` and `VIRTUAL_PROTO`? if you use `VIRTUAL_PROTO=https` i think the container needs to have certs and talk https properly.

**Comment by egorvas** [comment] 2016-06-27 10:23
@wader yes, without https settings everything works correctly, seems that my problem caused by certs or wring ports

**Comment by hk0i** [comment] 2018-01-06 07:59
So I just spent a good 8 hours or so with this, so I hope this helps someone.

There are two ways to add SSL. You can add the SSL either in the reverse proxy automagically by including the certs in your nginx-proxy certificates location - OR - if your container itself is expecting SSL, you can use the `VIRTUAL_PROTO` and `VIRTUAL_PORT` environment variables.

From my experience it's usually easier to let the proxy add SSL automagically. The way the magic works is that the certs need to be named `my.domain.com.crt` and `my.domain.com.key`... I spent a long time realizing my cert file was named `.cert` and not `.crt` and that is why my cert was not recognized.

Important excerpt from the documentation:

> The contents of `/path/to/certs` should contain the certificates and private keys for any virtual hosts in use. The certificate and keys should be named after the virtual host with a `.crt` and `.key` extension. For example, a container with `VIRTUAL_HOST=foo.bar.com` should have a `foo.bar.com.crt` and `foo.bar.com.key` file in the certs directory.

So in my case, instead of adding SSL inside my apache container, I let nginx-proxy add the SSL.
In my case I *did not* use `VIRTUAL_PROTO` and `VIRTUAL_PORT`.

As for `VIRTUAL_PORT` and `VIRTUAL_PROTO` (not adding SSL through the proxy but through your backend container) note that if you want nginx-proxy to talk to your container using SSL (instead of having nginx-proxy *add* the SSL) `VIRTUAL_PORT` is *only* needed if your container `EXPOSE`s more than one port (for example, 80 and 443). Then you would set your `VIRTUAL_PROTO` to 443. I have done this once before with a different project but I am having issues getting it to work now, so Instead of dealing with the extra variables I went with the more straight forward `nginx-proxy` SSL.

Hope that helps.

**Comment by qqilihq** [comment] 2018-01-15 15:29
> […] spent a long time realizing my cert file was named `.cert` and not `.crt` […]

Thanks for pointing this out. I'd probably have wasted another hour 👍

**Comment by nggary** [comment] 2018-03-14 10:43
@swoopdk Could you tell me how you could add 443 port to nginx-proxy default.conf? Because I'm facing the same problem as well.

**Comment by bjarnek** [comment] 2018-03-25 16:55
@nggary sorry i dont have anything of this running anymore that i know of :(

**Comment by zerogpm** [comment] 2018-06-20 22:46
Do you need to actually own the domain in order to make it works?

**Comment by dhamodar-adappt** [comment] 2019-07-03 11:50
> So I just spent a good 8 hours or so with this, so I hope this helps someone.
> 
> There are two ways to add SSL. You can add the SSL either in the reverse proxy automagically by including the certs in your nginx-proxy certificates location - OR - if your container itself is expecting SSL, you can use the `VIRTUAL_PROTO` and `VIRTUAL_PORT` environment variables.
> 
> From my experience it's usually easier to let the proxy add SSL automagically. The way the magic works is that the certs need to be named `my.domain.com.crt` and `my.domain.com.key`... I spent a long time realizing my cert file was named `.cert` and not `.crt` and that is why my cert was not recognized.
> 
> Important excerpt from the [documentation (readme)](https://github.com/jwilder/nginx-proxy):
> 
> > The contents of `/path/to/certs` should contain the certificates and private keys for any virtual hosts in use. The certificate and keys should be named after the virtual host with a `.crt` and `.key` extension. For example, a container with `VIRTUAL_HOST=foo.bar.com` should have a `foo.bar.com.crt` and `foo.bar.com.key` file in the certs directory.
> 
> So in my case, instead of adding SSL inside my apache container, I let nginx-proxy add the SSL.
> In my case I _did not_ use `VIRTUAL_PROTO` and `VIRTUAL_PORT`.
> 
> As for `VIRTUAL_PORT` and `VIRTUAL_PROTO` (not adding SSL through the proxy but through your backend container) note that if you want nginx-proxy to talk to your container using SSL (instead of having nginx-proxy _add_ the SSL) `VIRTUAL_PORT` is _only_ needed if your container `EXPOSE`s more than one port (for example, 80 and 443). Then you would set your `VIRTUAL_PROTO` to 443. I have done this once before with a different project but I am having issues getting it to work now, so Instead of dealing with the extra variables I went with the more straight forward `nginx-proxy` SSL.
> 
> Hope that helps.
add-on
cat example.com.crt intermediate.crt > example.com.crt need for third party .crt file
cd /etc/nginx/certs
sudo chmod -R 600 certs/

**Comment by dhamodar-adappt** [comment] 2019-07-03 11:50
additional data on .crt files updated

**Comment by buchdag** [comment] 2021-06-14 23:05
Outdated issue, closing.

**Closed by buchdag** 2021-06-14 23:05 UTC
