### ISSUE TITLE
Default server "_" causing SSL_POLICY and TLS 1.3 to break.

### ISSUE THREAD

**Issue by noaho** [nginx-proxy/nginx-proxy#1237] opened 2019-02-27 04:30 UTC
Hi, in the latest nginx, the first SSL server in the config file is influencing the other sites SSL config. 

Because the logic which uses a default self signed cert for sites not specified is first in the nginx config, SSL defaults are initialized, leaving TLS 1.1 on and stopping TLS 1.3 from working properly. 

Due to the way openssl works, it's currently impossible to select different TLS settings per site, on the same server, thus the default influences the other sections. Hence the "most strict" SSL configuration must be set as default, or the first configuration will override the others. 

Reference:
https://trac.nginx.org/nginx/ticket/844
http://nginx.org/en/docs/http/request_processing.html

This is the code in https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl that I am referring to:

"{{ if (and (exists "/etc/nginx/certs/default.crt") (exists "/etc/nginx/certs/default.key")) }}
server {
	server_name _;"

This is causing a host of issues below:
https://github.com/jwilder/nginx-proxy/issues/1181
https://github.com/jwilder/nginx-proxy/issues/1177

(Related issue, actually the cause of this issue)
https://github.com/jwilder/nginx-proxy/issues/765

You can also see this issue demonstrated over here:
https://github.com/nginxinc/docker-nginx/issues/190

Can we make the default cert for SSL disabled by default? Or somehow build the SSL_POLICY into the default site?

**Comment by Nottt** [comment] 2019-04-12 06:33
Any solution? I'd really like to enable TLS 1.3

**Comment by johnpyp** [comment] 2019-06-17 00:45
If other people are having this issue, you can solve it by using the docker-gen + nginx setup and deleting this part of the nginx.tmpl file https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L102-L116

**Comment by buchdag** [comment] 2021-06-15 09:27
@noaho correct me if I'm wrong, but the issue is also in the other direction: using the most strict SSL configuration set as a default would have the lest strict `SSL_POLICY` not working properly.

As your (and @kleptox in #1568) pointed you, this can't and won't be fixed by **nginx** devs.

Should we then consider that per-proxied container `SSL_POLICY` can't really work because of this limitation and that we should somehow change that to a global per proxy `SSL_POLICY`, with corresponding doc and rendered template warnings ?

**Comment by buchdag** [comment] 2023-12-19 22:10
This should have been fixed by #2186 and #2338

**Closed by buchdag** 2023-12-19 22:10 UTC
