### ISSUE TITLE
Doesn't work in swarm mode

### ISSUE THREAD

**Issue by LuisEnMarroquin** [nginx-proxy/nginx-proxy#1374] opened 2019-12-23 15:57 UTC
I have the following files:

* .env
```env
DOMAIN=localhost.com
```

* docker-whoami.yml
```yml
version: '3.7'

networks:
  default:
    name: nginx-proxy

volumes:
  certs:
  dhpar:
  vhost:
  htmls:

services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - dhpar:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - htmls:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  whoami:
    environment:
      VIRTUAL_HOST: whoami.${DOMAIN}
    image: jwilder/whoami
    ports:
      - 8000
```

When I run this in compose mode it works

```shell
docker-compose --project-name whoami -f docker-whoami.yml up -d --force-recreate --remove-orphans
```

![image](https://user-images.githubusercontent.com/35376824/71367379-810b8b80-256a-11ea-9dc1-63d4cae3c3ee.png)

But in swarm mode it just says 503

```shell
docker stack deploy -c docker-whoami.yml nginx
```

![image](https://user-images.githubusercontent.com/35376824/71367412-97b1e280-256a-11ea-8e81-33b2307a389e.png)

**Comment by Rakiah** [comment] 2019-12-24 01:26
same

**Comment by StiiCeva** [comment] 2020-01-12 17:55
declare a network and pass it to the services. It says in the docs that by default it uses 'bridge'.

**Comment by azhinu** [comment] 2020-06-19 07:29
If I correctly understand docker.sock:ro contains information about only local containers, not cluster.
If I deploy all services at one machine everything works great. But if I'll deploy at multiple machines Nginx proxy doesn't detect new container.

**Comment by pupattan** [comment] 2020-08-11 10:47
I am also facing the same issue

**Comment by netlander** [comment] 2020-09-23 16:20
Anyone found a good way to run this in Swarm/Stack mode?

**Comment by JonnyBeeGod** [comment] 2021-01-24 12:41
> If I correctly understand docker.sock:ro contains information about only local containers, not cluster.
> If I deploy all services at one machine everything works great. But if I'll deploy at multiple machines Nginx proxy doesn't detect new container.

Did you get it to work with docker swarm on one host? Because I am failing at this also. Tried adding an external, attachable overlay network like @StiiCeva proposed but still no luck.

**Comment by sl45sms** [comment] 2021-02-13 14:13
use deploy like : 
`
    deploy:
      replicas: 1
      restart_policy:
        delay: 0s
        window: 120s
      placement:
        constraints: [node.role == manager]
`

**Comment by tkw1536** [comment] 2022-04-10 17:01
Duplicate of https://github.com/nginx-proxy/nginx-proxy/issues/97

**Closed by tkw1536** 2022-04-10 17:01 UTC
Labels: status/duplicate
