### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by negue** [nginx-proxy/nginx-proxy#210] opened 2015-08-04 20:15 UTC
It seems that the proxy cant redirect to a virtual host

```
docker run -p 80:80 -p 443:443 \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  --name nginx-proxy \
  -d \
  jwilder/nginx-proxy
```

every container I run with

`docker run -e VIRTUAL_HOST=sub.domain.me ...`

i get

```
 [error] 58#58: *21 upstream timed out (110: Connection timed out) while connecting to upstream, client: X.X.X.X, server: sub.domain.me, request: "GET / HTTP/1.1", upstream: "http://172.X.X.X:80/", host: "sub.domain.me"
```

what am I doing wrong?

**Comment by md5** [comment] 2015-08-04 20:33
What do you mean by "every container I run"?

Either there's something wrong with your backend containers or there's something wrong with your host networking.

Over in #201, @leonpegg mentioned having a similar problem under a Fedora host, but he didn't provide any additional details.

**Comment by negue** [comment] 2015-08-04 22:27
I mean, every container with -e VIRTUAL_HOST dont wants to runs ...

I ran this command `docker run --rm appropriate/curl -f http://172.17.0.7/` and it couldnt connect to it

If I run my container with a `-p 80:80` it cant be executed because the proxy already runs on 80


I'm still a docker noob, is this a setting that containers can't talk to each other? Do I need to `--link ` my virtual host container?

**Comment by md5** [comment] 2015-08-05 01:48
You can try mapping your backend's port 80 to a different port like 8080 and see if you can connect. Beyond that, you'll have to use lower level tools like `tcpdump` to see what's happening with the packets.

Are you by any chance using Fedora? I'm not sure what problems @leonpegg was running into, but I could imagine having problems with bad `iptables` rules or something like that.

**Comment by negue** [comment] 2015-08-05 07:40
I exposed a new backends port for example 8801 , then started my container with `-e VIRTUAL_PORT=8801 ` but the generated default.conf still points to port 80 instead of 8801

**Comment by md5** [comment] 2015-08-05 11:28
That's not what I was suggesting. I was suggesting using something like `-p 8801:80` instead of `-p 80:80` and testing the backend container directly without `nginx-proxy`.

**Comment by leonpegg** [comment] 2015-08-05 13:29
@md5 when on my fedora 22 host docker containers can not talk to each other over there internal network but work when mapping a port to the host. I believe it is something to do with the docker configuration (container isolation maybe) but I have not yet confirmed this.
I have tested on server clean Fedora 22 installs both workstation and server and this problem persists, from the description of this issue it sounds as if its the same problem.

@negue What host OS are your running? As a test I would recommend installing virtualbox and using docker machine as this will ensure a docker configuration that works if you then no longer encounter the issue I would be very confident in saying it is an issue with the host/docker config.

**Comment by jodett** [comment] 2015-08-05 21:56
md5's solution should work for you, 
and here's some background for this
with -p 8801:80 (host:container) you map the hosts port 8801 to the containers port 80 (what's the standard port for a webserver), 
now your container is accessible to other processes on your computer like the nginx-proxy, 
if you write "-p 80:80" instead you try to map the hosts port 80, which is already occupied by nginx-proxy, to the containers port 80.

**Comment by negue** [comment] 2015-08-05 22:50
Running the backend container without nginx-proxy with `-p 8080:80` works. 

@leonpegg  I'm on Debian, I'll try running it in a virtual machine tomorrow 

I found the problem, my docker daemon was started with `--icc=false` so each container couldn't connect without a `--link ` (but I also tried that, didn't work^^)

**Comment by mickaelperrin** [comment] 2016-05-04 15:15
Are there any updates on this ? Is this a known issue that it doesn't work with `icc=false` even when using `links` ?

I run `Docker version 1.11.1, build 5604cbe` and I am using `docker-gen` alongside an `nginx` container. I try to run a `docker-compose` file with `nginx` set as an `external_links`.

If this not expected, I will try to produce a demo-bug configuration.

Thanks

**Comment by mickaelperrin** [comment] 2016-05-04 19:32
This drives me nuts. I really would like to know if I am going the wrong way, or if there is really a bug with docker or docker-nginx.

I created a demo-repo to reproduce this issue. Check it at https://github.com/mickaelperrin/docker-nginx-proxy-icc-bug.

Any help is appreciated.

**Comment by wader** [comment] 2016-05-04 20:32
Could the issue be that links are not bidirectional when it comes to establishing connections, the webapp container can connect to nginx but nginx can't connect to the webapp? looking at the docker code it seems to use [conntrack](https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_ip_tables.go#L139).  You can digg around with `ipnet netns ` if you want to make sure how it works.

Does it work if you add a link in nginx-proxy to webapp?

Maybe the new network support in docker can solve this without links if you need things to be more dynamic? but im not sure how that works together with icc false.

**Comment by mickaelperrin** [comment] 2016-05-04 21:35
@wader Thanks, you're right. `link` is not bi-directionnal, I thought it was (read to fast this [issue](https://github.com/docker/docker/issues/2588)). Starting the webapp before the nginx-proxy and setting a link from `nginx-proxy` to the `webapp` works...

Now that this project seems to support the new compose syntax, I will search in this direction and update this issue if I found a solution.

**Comment by wader** [comment] 2016-05-04 21:41
@mickaelperrin 👍 sounds good. Im interested in ways of firewalling containers too

**Comment by mickaelperrin** [comment] 2016-05-05 00:20
@wader Got it working with latest `jwilder/nginx-proxy` image and new docker v2 syntax. That's pretty straightforward, see https://github.com/mickaelperrin/docker-nginx-proxy-icc-bug/tree/solution1.

Next step, make it work with the decoupled version (docker-gen not publicly available), but this experiment seems to fail with that issue https://github.com/jwilder/nginx-proxy/issues/440. Will give it a new try, I maybe forgot to update the docker-gen container with the latest fix.

**Comment by mickaelperrin** [comment] 2016-05-05 00:38
Indeed, I forgot to update the `docker-gen` image to the very new which contains the fix. 

I can go further, but it still fails now with an Error 502 Bad Gateway and so seems to be related to #304, see my testing configuration at https://github.com/mickaelperrin/docker-nginx-proxy-icc-bug/tree/bug304.

Will add a comment to that issue too.

**Comment by tkw1536** [comment] 2022-04-16 09:25
Duplicate of #191

**Closed by tkw1536** 2022-04-16 09:25 UTC
Labels: status/duplicate
